version: "3"

volumes:
  mysql:

services:
  nginx:
    restart: always
    image: "nginx:1.21.6"
    ports:
      - "8000:8000"
    depends_on:
      - calendario

  mysql:
    platform: linux/amd64
    restart: always
    image: "mysql:8.0.28"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql:/var/lib/mysql

  calendario:
    restart: always
    ports:
      - 8087:8087
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    env_file:
      - .env
